import type {
  ChipWaveform,
  SfxParams,
  TrackerLayer,
  TrackerStep,
} from "@/lib/audio/chip8";
import { defaultSfxParams, noteToFreq } from "@/lib/audio/chip8";

const R = null as null;
const N = noteToFreq;

/** Full SFX params + export filename for `public/sounds/`. */
export type SfxLabPreset = {
  id: string;
  exportFile: string;
  label: string;
  category: "UI" | "Exploration" | "Combat" | "Items";
  params: SfxParams;
};

function sfx(p: Partial<SfxParams>): SfxParams {
  return { ...defaultSfxParams(), ...p };
}

/**
 * Presets aligned with the project’s intended `public/sounds/*.wav` set.
 * Legacy lab names (Blip, Coin, …) kept at end for quick experiments.
 */
export const SFX_LAB_PRESETS: SfxLabPreset[] = [
  {
    id: "ui-confirm",
    exportFile: "ui-confirm.wav",
    label: "UI — confirm / primary",
    category: "UI",
    params: sfx({
      waveform: "square",
      freqStart: 523,
      freqEnd: 784,
      durationMs: 110,
      attack: 0.02,
      decay: 0.25,
      sustain: 0.45,
      release: 0.35,
      duty: 0.5,
    }),
  },
  {
    id: "ui-cancel",
    exportFile: "ui-cancel.wav",
    label: "UI — cancel / back",
    category: "UI",
    params: sfx({
      waveform: "square",
      freqStart: 420,
      freqEnd: 196,
      durationMs: 140,
      attack: 0.03,
      decay: 0.35,
      sustain: 0.25,
      release: 0.4,
      duty: 0.45,
    }),
  },
  {
    id: "ui-hover",
    exportFile: "ui-hover.wav",
    label: "UI — hover tick",
    category: "UI",
    params: sfx({
      waveform: "triangle",
      freqStart: 1800,
      freqEnd: 2200,
      durationMs: 35,
      attack: 0.15,
      decay: 0.55,
      sustain: 0,
      release: 0.25,
      duty: 0.5,
    }),
  },
  {
    id: "ui-error",
    exportFile: "ui-error.wav",
    label: "UI — error / invalid",
    category: "UI",
    params: sfx({
      waveform: "saw",
      freqStart: 320,
      freqEnd: 120,
      durationMs: 260,
      attack: 0.02,
      decay: 0.45,
      sustain: 0.2,
      release: 0.35,
      duty: 0.5,
    }),
  },
  {
    id: "ui-ready",
    exportFile: "ui-ready.wav",
    label: "UI — ready toggle",
    category: "UI",
    params: sfx({
      waveform: "square",
      freqStart: 659,
      freqEnd: 880,
      durationMs: 160,
      attack: 0.04,
      decay: 0.2,
      sustain: 0.55,
      release: 0.25,
      duty: 0.5,
    }),
  },
  {
    id: "ui-start-game",
    exportFile: "ui-start-game.wav",
    label: "UI — start game / lock session",
    category: "UI",
    params: sfx({
      waveform: "saw",
      freqStart: 146,
      freqEnd: 392,
      durationMs: 320,
      attack: 0.08,
      decay: 0.3,
      sustain: 0.35,
      release: 0.35,
      duty: 0.5,
    }),
  },

  {
    id: "exploration-decision-pick",
    exportFile: "exploration-decision-pick.wav",
    label: "Exploration — highlight decision",
    category: "Exploration",
    params: sfx({
      waveform: "triangle",
      freqStart: 660,
      freqEnd: 740,
      durationMs: 55,
      attack: 0.12,
      decay: 0.5,
      sustain: 0.05,
      release: 0.3,
      duty: 0.5,
    }),
  },
  {
    id: "exploration-decision-lock",
    exportFile: "exploration-decision-lock.wav",
    label: "Exploration — commit decision",
    category: "Exploration",
    params: sfx({
      waveform: "square",
      freqStart: 220,
      freqEnd: 220,
      durationMs: 200,
      attack: 0.02,
      decay: 0.15,
      sustain: 0.55,
      release: 0.3,
      duty: 0.5,
    }),
  },
  {
    id: "exploration-roll",
    exportFile: "exploration-roll.wav",
    label: "Exploration — roll / resolve tick",
    category: "Exploration",
    params: sfx({
      waveform: "noise",
      freqStart: 400,
      freqEnd: 400,
      durationMs: 95,
      attack: 0.05,
      decay: 0.5,
      sustain: 0.15,
      release: 0.25,
      duty: 0.5,
    }),
  },
  {
    id: "exploration-success",
    exportFile: "exploration-success.wav",
    label: "Exploration — success sting",
    category: "Exploration",
    params: sfx({
      waveform: "square",
      freqStart: 392,
      freqEnd: 784,
      durationMs: 380,
      attack: 0.03,
      decay: 0.25,
      sustain: 0.5,
      release: 0.25,
      duty: 0.5,
    }),
  },
  {
    id: "exploration-fail",
    exportFile: "exploration-fail.wav",
    label: "Exploration — fail / danger",
    category: "Exploration",
    params: sfx({
      waveform: "triangle",
      freqStart: 380,
      freqEnd: 130,
      durationMs: 400,
      attack: 0.02,
      decay: 0.4,
      sustain: 0.2,
      release: 0.4,
      duty: 0.5,
    }),
  },
  {
    id: "room-enter",
    exportFile: "room-enter.wav",
    label: "Exploration — enter room",
    category: "Exploration",
    params: sfx({
      waveform: "triangle",
      freqStart: 196,
      freqEnd: 294,
      durationMs: 520,
      attack: 0.12,
      decay: 0.2,
      sustain: 0.45,
      release: 0.28,
      duty: 0.5,
    }),
  },
  {
    id: "clue-unlock",
    exportFile: "clue-unlock.wav",
    label: "Exploration — clue / journal unlock",
    category: "Exploration",
    params: sfx({
      waveform: "square",
      freqStart: 1046,
      freqEnd: 2093,
      durationMs: 240,
      attack: 0.02,
      decay: 0.35,
      sustain: 0.35,
      release: 0.3,
      duty: 0.5,
    }),
  },
  {
    id: "meta-villain-sting",
    exportFile: "meta-villain-sting.wav",
    label: "Exploration — meta / villain line",
    category: "Exploration",
    params: sfx({
      waveform: "saw",
      freqStart: 123,
      freqEnd: 82,
      durationMs: 720,
      attack: 0.15,
      decay: 0.35,
      sustain: 0.25,
      release: 0.3,
      duty: 0.5,
    }),
  },

  {
    id: "combat-encounter-start",
    exportFile: "combat-encounter-start.wav",
    label: "Combat — encounter start",
    category: "Combat",
    params: sfx({
      waveform: "saw",
      freqStart: 55,
      freqEnd: 311,
      durationMs: 340,
      attack: 0.06,
      decay: 0.35,
      sustain: 0.3,
      release: 0.35,
      duty: 0.5,
    }),
  },
  {
    id: "combat-player-swing",
    exportFile: "combat-player-swing.wav",
    label: "Combat — player swing",
    category: "Combat",
    params: sfx({
      waveform: "triangle",
      freqStart: 2400,
      freqEnd: 320,
      durationMs: 130,
      attack: 0.02,
      decay: 0.55,
      sustain: 0.1,
      release: 0.35,
      duty: 0.5,
    }),
  },
  {
    id: "combat-hit",
    exportFile: "combat-hit.wav",
    label: "Combat — hit connect",
    category: "Combat",
    params: sfx({
      waveform: "triangle",
      freqStart: 220,
      freqEnd: 55,
      durationMs: 200,
      attack: 0.01,
      decay: 0.48,
      sustain: 0.12,
      release: 0.35,
      duty: 0.5,
    }),
  },
  {
    id: "combat-miss",
    exportFile: "combat-miss.wav",
    label: "Combat — miss / whiff",
    category: "Combat",
    params: sfx({
      waveform: "square",
      freqStart: 1400,
      freqEnd: 600,
      durationMs: 85,
      attack: 0.05,
      decay: 0.55,
      sustain: 0.05,
      release: 0.35,
      duty: 0.35,
    }),
  },
  {
    id: "combat-crit",
    exportFile: "combat-crit.wav",
    label: "Combat — crit / strong hit",
    category: "Combat",
    params: sfx({
      waveform: "square",
      freqStart: 880,
      freqEnd: 1760,
      durationMs: 180,
      attack: 0.02,
      decay: 0.3,
      sustain: 0.45,
      release: 0.28,
      duty: 0.5,
    }),
  },
  {
    id: "combat-enemy-windup",
    exportFile: "combat-enemy-windup.wav",
    label: "Combat — enemy telegraph",
    category: "Combat",
    params: sfx({
      waveform: "saw",
      freqStart: 92,
      freqEnd: 247,
      durationMs: 420,
      attack: 0.1,
      decay: 0.3,
      sustain: 0.35,
      release: 0.28,
      duty: 0.5,
    }),
  },
  {
    id: "combat-enemy-hit",
    exportFile: "combat-enemy-hit.wav",
    label: "Combat — enemy hits party",
    category: "Combat",
    params: sfx({
      waveform: "noise",
      freqStart: 200,
      freqEnd: 200,
      durationMs: 280,
      attack: 0.02,
      decay: 0.42,
      sustain: 0.28,
      release: 0.3,
      duty: 0.5,
    }),
  },
  {
    id: "combat-victory",
    exportFile: "combat-victory.wav",
    label: "Combat — victory clear",
    category: "Combat",
    params: sfx({
      waveform: "square",
      freqStart: 392,
      freqEnd: 784,
      durationMs: 480,
      attack: 0.04,
      decay: 0.22,
      sustain: 0.5,
      release: 0.28,
      duty: 0.5,
    }),
  },
  {
    id: "combat-defeat",
    exportFile: "combat-defeat.wav",
    label: "Combat — defeat / wipe",
    category: "Combat",
    params: sfx({
      waveform: "triangle",
      freqStart: 196,
      freqEnd: 49,
      durationMs: 900,
      attack: 0.05,
      decay: 0.35,
      sustain: 0.25,
      release: 0.4,
      duty: 0.5,
    }),
  },

  {
    id: "item-tonic",
    exportFile: "item-tonic.wav",
    label: "Item — tonic heal",
    category: "Items",
    params: sfx({
      waveform: "triangle",
      freqStart: 523,
      freqEnd: 988,
      durationMs: 220,
      attack: 0.04,
      decay: 0.28,
      sustain: 0.4,
      release: 0.32,
      duty: 0.5,
    }),
  },
  {
    id: "item-balm",
    exportFile: "item-balm.wav",
    label: "Item — revival balm",
    category: "Items",
    params: sfx({
      waveform: "triangle",
      freqStart: 349,
      freqEnd: 880,
      durationMs: 340,
      attack: 0.06,
      decay: 0.25,
      sustain: 0.45,
      release: 0.28,
      duty: 0.5,
    }),
  },
  {
    id: "item-rest",
    exportFile: "item-rest.wav",
    label: "Item — sanctuary rest",
    category: "Items",
    params: sfx({
      waveform: "triangle",
      freqStart: 293,
      freqEnd: 196,
      durationMs: 650,
      attack: 0.12,
      decay: 0.2,
      sustain: 0.45,
      release: 0.28,
      duty: 0.5,
    }),
  },

  {
    id: "music-victory-sting",
    exportFile: "music-victory-sting.wav",
    label: "Music — victory sting (cathartic minor lift)",
    category: "Combat",
    params: sfx({
      waveform: "triangle",
      freqStart: 392,
      freqEnd: 987,
      durationMs: 520,
      attack: 0.04,
      decay: 0.22,
      sustain: 0.5,
      release: 0.32,
      duty: 0.5,
    }),
  },

  // Legacy quick shapes (audio lab originals)
  {
    id: "legacy-blip",
    exportFile: "chip-blip.wav",
    label: "Legacy — Blip",
    category: "UI",
    params: sfx({
      waveform: "square",
      freqStart: 880,
      freqEnd: 1320,
      durationMs: 80,
      attack: 0.05,
      decay: 0.35,
      sustain: 0.2,
      release: 0.4,
      duty: 0.5,
    }),
  },
  {
    id: "legacy-coin",
    exportFile: "chip-coin.wav",
    label: "Legacy — Coin",
    category: "UI",
    params: sfx({
      waveform: "square",
      freqStart: 988,
      freqEnd: 1318,
      durationMs: 160,
      attack: 0.02,
      decay: 0.2,
      sustain: 0.5,
      release: 0.5,
      duty: 0.5,
    }),
  },
  {
    id: "legacy-laser",
    exportFile: "chip-laser.wav",
    label: "Legacy — Laser",
    category: "UI",
    params: sfx({
      waveform: "saw",
      freqStart: 2400,
      freqEnd: 200,
      durationMs: 280,
      attack: 0.02,
      decay: 0.4,
      sustain: 0.15,
      release: 0.35,
      duty: 0.5,
    }),
  },
  {
    id: "legacy-noise-burst",
    exportFile: "chip-noise-burst.wav",
    label: "Legacy — Noise burst",
    category: "UI",
    params: sfx({
      waveform: "noise",
      freqStart: 400,
      freqEnd: 400,
      durationMs: 120,
      attack: 0.05,
      decay: 0.45,
      sustain: 0.2,
      release: 0.25,
      duty: 0.5,
    }),
  },
];

export type MusicLabPreset = {
  id: string;
  exportFile: string;
  label: string;
  category: "Music";
  bpm: number;
  waveform: ChipWaveform;
  duty: number;
  /** Default “long enough” export length = this many bar repeats. */
  musicLoops: number;
  steps: TrackerStep[];
  /**
   * Multiple independent layers (bass + lead + noise, etc.) mixed in the exporter / lab.
   * When omitted, `steps` + `waveform` + `duty` are a single layer at gain 1.
   */
  layers?: TrackerLayer[];
};

/** Resolve preset to mixer layers for `renderMultiTrackerLoop`. */
export function musicPresetToLayers(p: MusicLabPreset): TrackerLayer[] {
  if (p.layers && p.layers.length > 0) return p.layers;
  return [{ steps: p.steps, waveform: p.waveform, duty: p.duty, gain: 1 }];
}

/**
 * Music / ambient loops — full multi-layer mixes: modern metal groove (syncopated bass,
 * stacked mids) + ethereal top lines (Sleep Token–style space) + industrial noise beds
 * (Bad Omens–style texture). Chip fidelity; exported WAVs are the game source of truth.
 */
export const MUSIC_LAB_PRESETS: MusicLabPreset[] = [
  {
    id: "music-title-loop",
    exportFile: "music-title-loop.wav",
    label: "Music — title (F#m cathedral wash, breath)",
    category: "Music",
    bpm: 64,
    waveform: "triangle",
    duty: 0.52,
    musicLoops: 16,
    steps: [
      N("F#3"),
      N("A3"),
      N("C#4"),
      N("E4"),
      N("A3"),
      N("G#3"),
      N("F#3"),
      N("B3"),
      N("E4"),
      N("D4"),
      N("C#4"),
      N("B3"),
      N("A3"),
      N("G#3"),
      N("F#3"),
      N("E3"),
    ],
    layers: [
      {
        steps: [
          N("F#2"),
          R,
          N("C#3"),
          R,
          N("A2"),
          R,
          N("E3"),
          N("F#2"),
          R,
          N("B2"),
          R,
          N("G#2"),
          N("E3"),
          N("C#3"),
          R,
          N("F#2"),
        ],
        waveform: "square",
        duty: 0.48,
        gain: 0.52,
      },
      {
        steps: [
          N("F#3"),
          N("A3"),
          N("C#4"),
          N("E4"),
          N("A3"),
          N("G#3"),
          N("F#3"),
          N("B3"),
          N("E4"),
          N("D4"),
          N("C#4"),
          N("B3"),
          N("A3"),
          N("G#3"),
          N("F#3"),
          N("E3"),
        ],
        waveform: "saw",
        duty: 0.5,
        gain: 0.38,
      },
      {
        steps: [
          R,
          N("C#5"),
          R,
          N("A4"),
          R,
          R,
          N("B4"),
          R,
          N("G#4"),
          R,
          R,
          N("F#4"),
          R,
          N("E4"),
          R,
          R,
        ],
        waveform: "triangle",
        duty: 0.5,
        gain: 0.28,
      },
      {
        steps: [
          R,
          R,
          R,
          2600,
          R,
          R,
          R,
          2600,
          R,
          R,
          R,
          2600,
          R,
          R,
          R,
          2600,
        ],
        waveform: "noise",
        duty: 0.5,
        gain: 0.06,
      },
    ],
  },
  {
    id: "music-lobby-loop",
    exportFile: "music-lobby-loop.wav",
    label: "Music — lobby (B minor bounce, stacked hook)",
    category: "Music",
    bpm: 122,
    waveform: "square",
    duty: 0.42,
    musicLoops: 20,
    steps: [
      N("B4"),
      R,
      N("F#4"),
      R,
      R,
      N("B4"),
      N("C#5"),
      R,
      N("A4"),
      R,
      N("E5"),
      N("D5"),
      R,
      N("F#4"),
      R,
      N("B4"),
    ],
    layers: [
      {
        steps: [
          N("B2"),
          R,
          N("F#3"),
          N("B3"),
          N("B2"),
          R,
          N("E3"),
          N("G3"),
          N("A2"),
          R,
          N("C#4"),
          N("A3"),
          N("B2"),
          N("D3"),
          N("F#3"),
          N("E3"),
        ],
        waveform: "square",
        duty: 0.4,
        gain: 0.5,
      },
      {
        steps: [
          N("D4"),
          N("F#4"),
          N("B4"),
          R,
          N("D4"),
          N("C#4"),
          N("E4"),
          N("B3"),
          N("A3"),
          N("C#4"),
          N("E4"),
          N("A4"),
          N("F#4"),
          N("D4"),
          N("B3"),
          R,
        ],
        waveform: "saw",
        duty: 0.48,
        gain: 0.36,
      },
      {
        steps: [
          N("B4"),
          R,
          N("F#4"),
          R,
          R,
          N("B4"),
          N("C#5"),
          R,
          N("A4"),
          R,
          N("E5"),
          N("D5"),
          R,
          N("F#4"),
          R,
          N("B4"),
        ],
        waveform: "square",
        duty: 0.38,
        gain: 0.34,
      },
      {
        steps: [
          R,
          3000,
          R,
          3000,
          R,
          3000,
          R,
          3000,
          R,
          3000,
          R,
          3000,
          R,
          3000,
          R,
          3000,
        ],
        waveform: "noise",
        duty: 0.5,
        gain: 0.1,
      },
    ],
  },
  {
    id: "music-explore-loop",
    exportFile: "music-explore-loop.wav",
    label: "Music — explore (F# Phrygian layers, creeping grind)",
    category: "Music",
    bpm: 104,
    waveform: "saw",
    duty: 0.48,
    musicLoops: 18,
    steps: [
      R,
      R,
      N("C#4"),
      R,
      N("B3"),
      R,
      N("D4"),
      R,
      R,
      N("E4"),
      R,
      N("F#4"),
      R,
      N("G4"),
      R,
      N("F#4"),
    ],
    layers: [
      {
        steps: [
          N("F#2"),
          N("G2"),
          R,
          N("F#2"),
          N("E2"),
          N("B2"),
          R,
          N("F#2"),
          N("G2"),
          N("A2"),
          N("B2"),
          N("C#3"),
          N("F#2"),
          N("E2"),
          N("D3"),
          N("C#3"),
        ],
        waveform: "square",
        duty: 0.46,
        gain: 0.52,
      },
      {
        steps: [
          N("F#3"),
          N("G3"),
          N("F#3"),
          N("E3"),
          N("D3"),
          R,
          N("B3"),
          N("A3"),
          N("G3"),
          N("F#3"),
          N("E3"),
          N("D3"),
          N("C#4"),
          N("B3"),
          N("A3"),
          N("G3"),
        ],
        waveform: "saw",
        duty: 0.48,
        gain: 0.4,
      },
      {
        steps: [
          R,
          R,
          N("C#4"),
          R,
          N("B3"),
          R,
          N("D4"),
          R,
          R,
          N("E4"),
          R,
          N("F#4"),
          R,
          N("G4"),
          R,
          N("F#4"),
        ],
        waveform: "triangle",
        duty: 0.5,
        gain: 0.28,
      },
      {
        steps: [
          2600,
          R,
          R,
          R,
          2600,
          R,
          R,
          2600,
          R,
          R,
          R,
          2600,
          R,
          R,
          R,
          2600,
        ],
        waveform: "noise",
        duty: 0.5,
        gain: 0.09,
      },
    ],
  },
  {
    id: "music-tension-loop",
    exportFile: "music-tension-loop.wav",
    label: "Music — tension (chromatic stack + noise spiral)",
    category: "Music",
    bpm: 168,
    waveform: "saw",
    duty: 0.5,
    musicLoops: 24,
    steps: [
      N("E5"),
      N("F5"),
      N("F#5"),
      N("G5"),
      N("C#5"),
      N("D5"),
      N("E5"),
      N("B5"),
      N("B5"),
      N("A5"),
      N("G5"),
      N("F#5"),
      N("F5"),
      N("E5"),
      N("D5"),
      N("C#5"),
    ],
    layers: [
      {
        steps: [
          N("A2"),
          N("A#2"),
          N("B2"),
          N("C3"),
          N("F#2"),
          N("G2"),
          N("A2"),
          N("E3"),
          N("E3"),
          N("D3"),
          N("C3"),
          N("B2"),
          N("A#2"),
          N("A2"),
          N("G2"),
          N("F#2"),
        ],
        waveform: "square",
        duty: 0.44,
        gain: 0.5,
      },
      {
        steps: [
          N("A3"),
          N("A#3"),
          N("B3"),
          N("C4"),
          N("F#3"),
          N("G3"),
          N("A3"),
          N("E4"),
          N("E4"),
          N("D4"),
          N("C4"),
          N("B3"),
          N("A#3"),
          N("A3"),
          N("G3"),
          N("F#3"),
        ],
        waveform: "saw",
        duty: 0.5,
        gain: 0.38,
      },
      {
        steps: [
          N("E5"),
          N("F5"),
          N("F#5"),
          N("G5"),
          N("C#5"),
          N("D5"),
          N("E5"),
          N("B5"),
          N("B5"),
          N("A5"),
          N("G5"),
          N("F#5"),
          N("F5"),
          N("E5"),
          N("D5"),
          N("C#5"),
        ],
        waveform: "triangle",
        duty: 0.5,
        gain: 0.3,
      },
      {
        steps: [
          3000,
          2800,
          2600,
          2400,
          3000,
          2900,
          2700,
          2500,
          3000,
          2800,
          2600,
          2400,
          3000,
          2800,
          2600,
          2400,
        ],
        waveform: "noise",
        duty: 0.5,
        gain: 0.11,
      },
    ],
  },
  {
    id: "music-combat-loop",
    exportFile: "music-combat-loop.wav",
    label: "Music — combat (F#m gallop, bass + saw + hats)",
    category: "Music",
    bpm: 172,
    waveform: "square",
    duty: 0.48,
    musicLoops: 28,
    steps: [
      N("F#3"),
      N("F#3"),
      N("A3"),
      N("C#4"),
      N("F#3"),
      N("E3"),
      N("B3"),
      N("F#4"),
      N("E4"),
      N("D4"),
      N("C#4"),
      N("B3"),
      N("F#3"),
      N("A3"),
      N("D4"),
      N("E4"),
    ],
    layers: [
      {
        steps: [
          N("F#2"),
          N("F#2"),
          N("A2"),
          N("C#3"),
          N("F#2"),
          N("E2"),
          N("B2"),
          N("F#3"),
          N("E3"),
          N("D3"),
          N("C#3"),
          N("B2"),
          N("F#2"),
          N("A2"),
          N("D3"),
          N("E3"),
        ],
        waveform: "square",
        duty: 0.46,
        gain: 0.48,
      },
      {
        steps: [
          N("F#3"),
          R,
          N("C#4"),
          N("F#4"),
          N("A3"),
          R,
          N("B3"),
          N("D4"),
          N("C#4"),
          R,
          N("A3"),
          R,
          N("F#3"),
          R,
          N("A3"),
          N("B3"),
        ],
        waveform: "saw",
        duty: 0.45,
        gain: 0.26,
      },
      {
        steps: [
          N("F#3"),
          N("F#3"),
          N("A3"),
          N("C#4"),
          N("F#3"),
          N("E3"),
          N("B3"),
          N("F#4"),
          N("E4"),
          N("D4"),
          N("C#4"),
          N("B3"),
          N("F#3"),
          N("A3"),
          N("D4"),
          N("E4"),
        ],
        waveform: "square",
        duty: 0.42,
        gain: 0.34,
      },
      {
        steps: [
          R,
          2800,
          R,
          2800,
          R,
          2800,
          R,
          2800,
          R,
          2800,
          R,
          2800,
          R,
          2800,
          R,
          2800,
        ],
        waveform: "noise",
        duty: 0.5,
        gain: 0.1,
      },
    ],
  },
  {
    id: "music-boss-loop",
    exportFile: "music-boss-loop.wav",
    label: "Music — boss (C / F# tritone doom stack)",
    category: "Music",
    bpm: 48,
    waveform: "saw",
    duty: 0.52,
    musicLoops: 16,
    steps: [
      N("C4"),
      N("B3"),
      N("A#3"),
      N("G#3"),
      N("G4"),
      N("F#4"),
      N("E4"),
      N("D#4"),
      N("C5"),
      R,
      N("B4"),
      N("A#4"),
      N("G#4"),
      N("G4"),
      N("F#4"),
      N("E4"),
    ],
    layers: [
      {
        steps: [
          N("C2"),
          R,
          N("G2"),
          N("C3"),
          N("F#3"),
          R,
          N("G2"),
          N("B2"),
          N("C3"),
          N("D#3"),
          N("G2"),
          R,
          N("C2"),
          N("F2"),
          N("G#2"),
          N("B2"),
        ],
        waveform: "saw",
        duty: 0.52,
        gain: 0.54,
      },
      {
        steps: [
          N("G2"),
          R,
          N("C3"),
          R,
          N("F#3"),
          N("B2"),
          R,
          N("D#3"),
          N("G3"),
          R,
          N("C3"),
          R,
          N("F2"),
          N("C3"),
          N("G#2"),
          N("D#3"),
        ],
        waveform: "square",
        duty: 0.42,
        gain: 0.36,
      },
      {
        steps: [
          N("C4"),
          N("B3"),
          N("A#3"),
          N("G#3"),
          N("G4"),
          N("F#4"),
          N("E4"),
          N("D#4"),
          N("C5"),
          R,
          N("B4"),
          N("A#4"),
          N("G#4"),
          N("G4"),
          N("F#4"),
          N("E4"),
        ],
        waveform: "triangle",
        duty: 0.5,
        gain: 0.24,
      },
      {
        steps: [
          R,
          2400,
          R,
          R,
          2400,
          R,
          2400,
          R,
          R,
          2400,
          R,
          R,
          2400,
          R,
          R,
          2400,
        ],
        waveform: "noise",
        duty: 0.5,
        gain: 0.1,
      },
    ],
  },

  {
    id: "ambient-entrance",
    exportFile: "ambient-entrance.wav",
    label: "Ambient — entrance (E add9 veil, slow bloom)",
    category: "Music",
    bpm: 50,
    waveform: "triangle",
    duty: 0.5,
    musicLoops: 20,
    steps: [
      N("E3"),
      N("G#3"),
      N("B3"),
      N("E4"),
      N("G#3"),
      R,
      N("B3"),
      N("E4"),
      N("D#3"),
      N("F#3"),
      N("A3"),
      N("B3"),
      N("C#4"),
      R,
      N("B3"),
      N("A3"),
    ],
    layers: [
      {
        steps: [
          N("E2"),
          R,
          R,
          N("B2"),
          N("E3"),
          R,
          R,
          N("G#3"),
          N("B2"),
          R,
          N("E3"),
          R,
          N("D#3"),
          R,
          N("B2"),
          R,
        ],
        waveform: "triangle",
        duty: 0.5,
        gain: 0.5,
      },
      {
        steps: [
          N("E3"),
          N("G#3"),
          N("B3"),
          N("E4"),
          N("G#3"),
          R,
          N("B3"),
          N("E4"),
          N("D#3"),
          N("F#3"),
          N("A3"),
          N("B3"),
          N("C#4"),
          R,
          N("B3"),
          N("A3"),
        ],
        waveform: "saw",
        duty: 0.48,
        gain: 0.38,
      },
      {
        steps: [
          N("B4"),
          R,
          N("E5"),
          R,
          N("G#5"),
          R,
          N("B4"),
          R,
          R,
          N("E5"),
          R,
          N("G#4"),
          R,
          R,
          N("F#4"),
          R,
        ],
        waveform: "triangle",
        duty: 0.5,
        gain: 0.26,
      },
      {
        steps: [
          R,
          R,
          R,
          2600,
          R,
          R,
          R,
          R,
          R,
          R,
          R,
          2600,
          R,
          R,
          R,
          R,
        ],
        waveform: "noise",
        duty: 0.5,
        gain: 0.05,
      },
    ],
  },
  {
    id: "ambient-registry",
    exportFile: "ambient-registry.wav",
    label: "Ambient — registry (altered crawl, stacked unease)",
    category: "Music",
    bpm: 54,
    waveform: "triangle",
    duty: 0.48,
    musicLoops: 20,
    steps: [
      N("C#4"),
      N("D4"),
      N("F4"),
      N("F#4"),
      N("A#4"),
      N("G#4"),
      N("F4"),
      N("E4"),
      N("D#4"),
      N("D4"),
      N("C#4"),
      N("B3"),
      N("A#3"),
      N("G#3"),
      N("F#3"),
      N("E3"),
    ],
    layers: [
      {
        steps: [
          N("C#3"),
          N("D3"),
          N("F3"),
          N("F#3"),
          N("A#3"),
          R,
          N("G#3"),
          N("F3"),
          N("E3"),
          N("D#3"),
          N("D3"),
          N("C#3"),
          N("B2"),
          R,
          N("C#3"),
          R,
        ],
        waveform: "square",
        duty: 0.48,
        gain: 0.52,
      },
      {
        steps: [
          N("C#4"),
          N("D4"),
          N("F4"),
          N("F#4"),
          N("A#4"),
          N("G#4"),
          N("F4"),
          N("E4"),
          N("D#4"),
          N("D4"),
          N("C#4"),
          N("B3"),
          N("A#3"),
          N("G#3"),
          N("F#3"),
          N("E3"),
        ],
        waveform: "saw",
        duty: 0.5,
        gain: 0.4,
      },
      {
        steps: [
          R,
          N("F#4"),
          R,
          N("A#4"),
          R,
          R,
          N("C#5"),
          R,
          R,
          N("D#5"),
          R,
          N("C#5"),
          R,
          N("B4"),
          R,
          N("A#4"),
        ],
        waveform: "triangle",
        duty: 0.5,
        gain: 0.22,
      },
      {
        steps: [
          2600,
          R,
          R,
          2600,
          R,
          2600,
          R,
          R,
          R,
          2600,
          R,
          R,
          2600,
          R,
          R,
          R,
        ],
        waveform: "noise",
        duty: 0.5,
        gain: 0.08,
      },
    ],
  },
  {
    id: "ambient-library",
    exportFile: "ambient-library.wav",
    label: "Ambient — library (Am descent, layered lament)",
    category: "Music",
    bpm: 58,
    waveform: "saw",
    duty: 0.42,
    musicLoops: 18,
    steps: [
      N("A3"),
      N("C4"),
      N("E4"),
      N("A4"),
      N("G4"),
      N("F#4"),
      N("E4"),
      N("D4"),
      N("C4"),
      N("B3"),
      N("A3"),
      N("G3"),
      N("F#3"),
      N("E3"),
      N("D3"),
      N("C3"),
    ],
    layers: [
      {
        steps: [
          N("A2"),
          N("C3"),
          N("E3"),
          N("A3"),
          N("G3"),
          N("F#3"),
          N("E3"),
          N("D3"),
          N("C3"),
          N("B2"),
          N("A2"),
          N("G2"),
          N("F#2"),
          N("E2"),
          N("D2"),
          R,
        ],
        waveform: "saw",
        duty: 0.52,
        gain: 0.5,
      },
      {
        steps: [
          N("A3"),
          N("C4"),
          N("E4"),
          N("A4"),
          N("G4"),
          N("F#4"),
          N("E4"),
          N("D4"),
          N("C4"),
          N("B3"),
          N("A3"),
          N("G3"),
          N("F#3"),
          N("E3"),
          N("D3"),
          N("C3"),
        ],
        waveform: "triangle",
        duty: 0.5,
        gain: 0.36,
      },
      {
        steps: [
          N("E5"),
          R,
          N("C5"),
          R,
          N("A4"),
          R,
          R,
          N("G4"),
          R,
          N("F#4"),
          R,
          N("E4"),
          R,
          N("D4"),
          R,
          N("C4"),
        ],
        waveform: "triangle",
        duty: 0.5,
        gain: 0.26,
      },
      {
        steps: [
          R,
          R,
          2600,
          R,
          R,
          R,
          2600,
          R,
          R,
          R,
          R,
          2600,
          R,
          R,
          R,
          R,
        ],
        waveform: "noise",
        duty: 0.5,
        gain: 0.06,
      },
    ],
  },
  {
    id: "ambient-servants",
    exportFile: "ambient-servants.wav",
    label: "Ambient — servants (G Phrygian industrial grid)",
    category: "Music",
    bpm: 92,
    waveform: "square",
    duty: 0.26,
    musicLoops: 22,
    steps: [
      N("G4"),
      R,
      N("G4"),
      R,
      N("D4"),
      R,
      N("G4"),
      R,
      N("F4"),
      R,
      N("Eb4"),
      R,
      N("D4"),
      R,
      N("C4"),
      R,
    ],
    layers: [
      {
        steps: [
          N("G2"),
          N("G3"),
          N("G2"),
          N("D3"),
          N("G2"),
          N("Bb3"),
          N("G2"),
          N("D4"),
          N("G2"),
          N("F3"),
          N("G2"),
          N("Eb3"),
          N("G2"),
          N("C4"),
          N("G2"),
          N("Bb3"),
        ],
        waveform: "square",
        duty: 0.24,
        gain: 0.5,
      },
      {
        steps: [
          N("G3"),
          N("Bb3"),
          N("D4"),
          N("G4"),
          N("F4"),
          N("Eb4"),
          N("D4"),
          N("C4"),
          N("Bb3"),
          N("Ab3"),
          N("G3"),
          N("F3"),
          N("Eb3"),
          N("D3"),
          N("C3"),
          N("Bb2"),
        ],
        waveform: "saw",
        duty: 0.5,
        gain: 0.38,
      },
      {
        steps: [
          N("G4"),
          R,
          N("G4"),
          R,
          N("D4"),
          R,
          N("G4"),
          R,
          N("F4"),
          R,
          N("Eb4"),
          R,
          N("D4"),
          R,
          N("C4"),
          R,
        ],
        waveform: "square",
        duty: 0.35,
        gain: 0.3,
      },
      {
        steps: [
          3000,
          R,
          2800,
          R,
          3000,
          R,
          2600,
          R,
          3000,
          R,
          2800,
          R,
          3000,
          R,
          2700,
          R,
        ],
        waveform: "noise",
        duty: 0.5,
        gain: 0.13,
      },
    ],
  },
  {
    id: "ambient-dining",
    exportFile: "ambient-dining.wav",
    label: "Ambient — dining (false elegance, layered wrong-notes)",
    category: "Music",
    bpm: 60,
    waveform: "triangle",
    duty: 0.5,
    musicLoops: 18,
    steps: [
      N("F3"),
      N("A3"),
      N("C4"),
      N("E4"),
      N("D4"),
      N("C#4"),
      N("C4"),
      N("B3"),
      N("Bb3"),
      N("A3"),
      N("Ab3"),
      N("G3"),
      N("Gb3"),
      N("F3"),
      N("E3"),
      N("D3"),
    ],
    layers: [
      {
        steps: [
          N("F3"),
          N("A3"),
          N("C4"),
          N("E4"),
          N("D4"),
          N("C#4"),
          N("C4"),
          N("B3"),
          N("Bb3"),
          N("A3"),
          N("Ab3"),
          N("G3"),
          N("Gb3"),
          N("F3"),
          N("E3"),
          N("D3"),
        ],
        waveform: "triangle",
        duty: 0.5,
        gain: 0.5,
      },
      {
        steps: [
          N("F3"),
          N("A3"),
          N("C4"),
          N("E5"),
          N("D5"),
          N("C#5"),
          N("C5"),
          N("B4"),
          N("Bb4"),
          N("A4"),
          N("Ab4"),
          N("G4"),
          N("Gb4"),
          N("F4"),
          N("E4"),
          N("D4"),
        ],
        waveform: "saw",
        duty: 0.46,
        gain: 0.34,
      },
      {
        steps: [
          N("A4"),
          N("C5"),
          N("E5"),
          N("G5"),
          N("F#5"),
          N("F5"),
          N("E5"),
          N("D#5"),
          N("D5"),
          N("C#5"),
          N("C5"),
          N("B4"),
          N("Bb4"),
          N("A4"),
          N("Ab4"),
          N("G4"),
        ],
        waveform: "triangle",
        duty: 0.5,
        gain: 0.26,
      },
      {
        steps: [
          R,
          2400,
          R,
          2400,
          R,
          R,
          2400,
          R,
          R,
          2400,
          R,
          R,
          2400,
          R,
          R,
          R,
        ],
        waveform: "noise",
        duty: 0.5,
        gain: 0.07,
      },
    ],
  },
  {
    id: "ambient-boss",
    exportFile: "ambient-boss.wav",
    label: "Ambient — boss (F# tritone void, sub + grain)",
    category: "Music",
    bpm: 40,
    waveform: "saw",
    duty: 0.55,
    musicLoops: 14,
    steps: [
      N("F#4"),
      N("E4"),
      N("D#4"),
      N("C#4"),
      N("B3"),
      N("A#3"),
      N("G#3"),
      N("F#3"),
      N("E4"),
      N("D4"),
      N("C4"),
      N("B3"),
      N("A#3"),
      N("G#3"),
      N("F#3"),
      N("E3"),
    ],
    layers: [
      {
        steps: [
          N("F#2"),
          R,
          N("C#3"),
          R,
          N("F#2"),
          N("B2"),
          N("D#3"),
          N("G3"),
          N("F#2"),
          R,
          N("C#3"),
          N("A#2"),
          N("F#2"),
          N("G#2"),
          N("B2"),
          N("C#3"),
        ],
        waveform: "saw",
        duty: 0.55,
        gain: 0.56,
      },
      {
        steps: [
          N("C#3"),
          R,
          N("F#3"),
          R,
          N("E3"),
          N("D#3"),
          N("C#3"),
          N("B2"),
          N("A#3"),
          N("G3"),
          N("F#3"),
          N("E3"),
          N("D#3"),
          N("C#3"),
          N("B2"),
          N("A#2"),
        ],
        waveform: "square",
        duty: 0.4,
        gain: 0.38,
      },
      {
        steps: [
          N("F#4"),
          N("E4"),
          N("D#4"),
          N("C#4"),
          N("B3"),
          N("A#3"),
          N("G#3"),
          N("F#3"),
          N("E4"),
          N("D4"),
          N("C4"),
          N("B3"),
          N("A#3"),
          N("G#3"),
          N("F#3"),
          N("E3"),
        ],
        waveform: "triangle",
        duty: 0.5,
        gain: 0.22,
      },
      {
        steps: [
          2400,
          R,
          R,
          R,
          2400,
          R,
          R,
          2400,
          R,
          R,
          R,
          2400,
          R,
          R,
          R,
          R,
        ],
        waveform: "noise",
        duty: 0.5,
        gain: 0.12,
      },
    ],
  },
];

export const SFX_PRESETS_BY_ID: Record<string, SfxLabPreset> = Object.fromEntries(
  SFX_LAB_PRESETS.map((p) => [p.id, p]),
);

export const MUSIC_PRESETS_BY_ID: Record<string, MusicLabPreset> =
  Object.fromEntries(MUSIC_LAB_PRESETS.map((p) => [p.id, p]));
